package.json
packages/button/package.json
packages/themes/package.json
packages/typography/package.json
packages/vars/package.json
tools/rollup/addCssImports.js

build fix: all names of the build CSS files in the packages will be in the lowercase

Fixed css files path in builds

---

bin/buildThemes.js
packages/themes/README.md
packages/themes/src/index.ts

fix(themes): fixed build issues for default theme

---

.github/CONTRIBUTING.md
docs/Contributing.stories.mdx

Merged the content of .md and .mdx files, removed redundancy

feature: Improved contributing documentation [#HEYUI-121] 

---

packages/collapse/CHANGELOG.md
packages/collapse/README.md
packages/collapse/package.json
packages/collapse/src/Collapse.tsx
packages/collapse/src/Collapse.types.tsx
packages/collapse/src/__tests__/Collapse.snapshot.test.tsx
packages/collapse/src/__tests__/Collapse.test.tsx
packages/collapse/src/__tests__/__snapshots__/Collapse.snapshot.test.tsx.snap
packages/collapse/src/__tests__/getCollapseStyles.test.tsx
packages/collapse/src/__tests__/useCollapse.test.tsx
packages/collapse/src/docs/Component.stories.mdx
packages/collapse/src/docs/Description.mdx
packages/collapse/src/hooks/UseCollapse.types.ts
packages/collapse/src/hooks/useCollapse.ts
packages/collapse/src/index.ts
packages/collapse/src/styles/default.module.css
packages/collapse/src/utils/getCollapseStyles.ts
packages/collapse/tsconfig.json

The first version of the collapse component.
Auxiliary component for hiding or showing content.

feat(collapse): the first version of the collapse component

---

.storybook/blocks/Status/Status.module.css
.storybook/blocks/Status/Status.tsx
docs/ComponentStatuses.stories.mdx
package-lock.json
packages/themes/src/docs/Component.stories.mdx
packages/typography/src/docs/Component.stories.mdx
packages/vars/src/docs/Component.stories.mdx

feat/HEYUI-131 Change 'In Development' status as 'Ready'

---

packages/logo/package.json
packages/logo/src/Logo.types.ts

https://heycar.atlassian.net/jira/software/projects/HEYUI/boards/312?selectedIssue=HEYUI-147
made fontsize optional

refactor(logo): make fontsize optional

---

packages/switch/package.json
packages/switch/src/Switch.tsx

clean default props on switch for test coverage

refactor(switch): clean default props on switch for test coverage

---

packages/collapse/package.json
packages/collapse/src/Collapse.tsx
packages/logo/package.json

Clean default props on collapse for test coverage

refactor(collapse): clean default props on collapse for test coverage

---

.github/pull_request_template.md
docs/Screenshots.stories.mdx
package-lock.json

Add docker screenshot test command to the checklist for pull requests
For working with SH tests locally you should use:
- npm run test:sh:docker - for checking

docs(pull request template): add docker screenshot test command to the checklist for pull requests

---

packages/accordion/package.json
packages/button/package.json
packages/button/src/__tests__/Button.test.tsx
packages/button/src/styles/default.module.css
packages/chip/package.json
packages/icons/package.json

Issue ref: https://heycar.atlassian.net/jira/software/projects/HEYUI/boards/312?issueType=10766&selectedIssue=HEYUI-132
added nowrap white space to Prevent multiline text on buttons
added nowrap white space to Prevent multiline text on buttons
added nowrap white space to Prevent multiline text on buttons
npm run start
and go [here](http://localhost:9009/?path=/story/components-button--button&args=children:Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Button+CTA+Butt …

fix(button): prevent multiline text on buttons

---

.storybook/preview.js
docs/IntegrationPath1.stories.mdx
docs/IntegrationPath2.stories.mdx
docs/IntegrationPath3.stories.mdx
docs/IntegrationWorkFlow.stories.mdx

Adding 4 new pages to the storybook regarding the integration workflow documentation
Integration Workflows
1. Happy Path
2. Almost Happy Path
3. Adding New Component
- [*] Documentation change

feature: integration workflow pages [#HEYUI-175]

---

packages/form-control/src/docs/Component.stories.mdx

feat(form-control): improve documentation part

---

bin/publishCi.sh
packages/form-control/src/FormControl.tsx

feat(form-control): improve performance

---

.github/auto_assign-issues.yml
.github/auto_assign.yml

update auto assigns

---

.github/CONTRIBUTING.md

docs: add Step-by-step contribution manual for the Contributing section

---

docs/ComponentStatuses.stories.mdx

fixing typo from statuses to status

fix: fixing typo from statuses to status

---

.github/CONTRIBUTING.md

Small update in the documentation, I was not able to do commits until I installed husky git hooks.

docs(contributing): add husky install step

---

.github/auto_assign-issues.yml
.github/auto_assign.yml

fix: assignees updated

---

docs/IntegrationWorkFlow.stories.mdx

Add a dot for integration flow text

refactor(document): add a dot for integration flow text

---

packages/badge/package.json

Set line-height for badge to 20 px
set line-height for badge to 20 px

chore(badge): set line-height for badge to 20 px

---

packages/badge/README.md

fixes the Badge style mismatch

fix(badge): fixes the Badge style mismatch

---

packages/icons/README.md

updating the shopping cart icon

fix(icon): updating the shopping cart icon

---

docs/IntegrationPath3.stories.mdx

add based epic link on the documentation

docs(integration): add based epic link on the documentation

---

.github/CONTRIBUTING.md
docs/IntegrationPath1.stories.mdx
docs/IntegrationPath2.stories.mdx
docs/IntegrationPath3.stories.mdx

update channels as global-design-system-community channel

docs(documentation): update channels as global-design-system-community channel

---

packages/typography/src/Typography.types.ts

Extend the typography component to accept more props

feat: Extend the typography component to accept more props

---

packages/dropdown/src/Dropdown.tsx
packages/dropdown/src/Dropdown.types.ts
packages/dropdown/src/docs/Description.mdx

Added an error state
Added an error state

fix(dropdown): adds error state

---

packages/dropdown/src/Dropdown.tsx
packages/dropdown/src/Dropdown.types.ts

fix(dropdown): added input ref
fix(dropdown): added input ref

fix(dropdown): added input ref

---

package-lock.json

This adds correct `package-lock.json `for pagination PR that was merged.

fix(package-lock.json): updated for pagination

---

package-lock.json
packages/dropdown/src/components/DropdownOption.types.ts

Added `number` type to Dropdown's `value` type
ticket: https://heycar.atlassian.net/browse/HEYUI-247

feat(input): add number type to dropdown value type #145

---

.github/auto_assign-issues.yml
.github/auto_assign.yml

[HEYUI-249] - Update auto assignee and reviewer list

---

packages/badge/src/docs/Component.stories.mdx
packages/button/src/docs/Component.stories.mdx

HEYUI-260
add icon controls to canvas for badge and button

docs(badge button): add icon controls to canvas for badge and button

---

packages/colors/docs/Component.stories.mdx

add colors component information under atoms

docs(colors): add colors component information under atoms

---

packages/button/src/Button.tsx
packages/button/src/__tests__/__snapshots__/Button.snapshot.test.tsx.snap
packages/button/src/components/ButtonIcon.tsx
packages/button/src/styles/default.module.css

update margins for icon left right as 20px

feat(button): update margins for icon left right as 20px

---

packages/button/src/__tests__/Button.snapshot.test.tsx
packages/review-rating/src/__tests__/ReviewRating.snapshot.test.tsx
packages/review-rating/src/__tests__/ReviewRatingHelpers.test.ts
packages/review-rating/src/__tests__/__snapshots__/ReviewRating.snapshot.test.tsx.snap
packages/review-rating/src/utils/reviewRatingHelpers.ts

add unit and snapshot tests for reviewRating components and utils
HEYUI-311

test(review-rating): add unit and snapshot tests

---

packages/typography/src/docs/Description.mdx

chore(docs): add all varient example to typography docs

---

packages/review-rating/src/styles/default.module.css

There was some invalid CSS. issue is now fixed
HEYUI-322

fix(review-rating): fix CSS issue

---

packages/grid/package.json
packages/grid/src/docs/Component.stories.mdx
packages/input/src/docs/Component.stories.mdx

chore: update documentation and grid export

---

packages/header/src/Header.tsx
packages/header/src/__tests__/headerItemHelpers.test.tsx
packages/header/src/__tests__/useNavigationItem.test.tsx
packages/header/src/components/LanguageList.tsx
packages/header/src/components/LanguageList.types.ts
packages/header/src/components/Navigation.types.ts
packages/header/src/components/NavigationBurgerMenu.tsx
packages/header/src/components/NavigationDropdown.tsx
packages/header/src/components/SubNav.tsx
packages/header/src/hooks/useNavigationItem.ts
packages/header/src/styles/subNav.module.css
packages/header/src/utils/headerItemHelpers.tsx

close menu when any page changing item is clicked + if show all link has custom test send that to tracking
HEYUI-358

fix(header): some burger menu issues

---

packages/vars/src/typography.css

This PR changes the `font-size` of the `<Typography variant="h2"/>` on mobile devices, according to design changes requested on https://heycar.atlassian.net/browse/IN-285

fix(typography): change h2 font-size on mobile
